<a href="https://colab.research.google.com/github/gvasquezcrs/python_ia_aplicada/blob/main/Aula_5_Python_Inteligencia_Artificial_Aplicada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 5

In [ ]:
import pandas as pd
import random

# Definir posibles valores para las columnas
nombres_productos_posibles = [
    'Laptop', 'Smartphone', 'Tablet', 'Smartwatch', 'Auriculares', 'Teclado', 'Mouse', 'Monitor', 'Impresora', 'Altavoz',
    'Cámara', 'Disco Duro', 'Router', 'Webcam', 'Micrófono', 'Gafas VR', 'Consola', 'Control Remoto', 'Proyector', 'Batería Externa'
]
categorias_posibles = ['Electrónica', 'Hogar', 'Oficina', 'Entretenimiento', 'Accesorios']

# Seleccionar 10 nombres de productos únicos aleatoriamente
productos_elegidos = random.sample(nombres_productos_posibles, 10)

# Generar datos para las 10 filas
data = {
    'Nombre de producto': productos_elegidos,
    'Categoria': [random.choice(categorias_posibles) for _ in range(10)],
    'Precio': [round(random.uniform(50, 1500), 2) for _ in range(10)],
    'Stock': [random.randint(10, 100) for _ in range(10)]
}

# Crear el DataFrame
df_productos = pd.DataFrame(data)

# Mostrar el DataFrame
display(df_productos)

  Nombre de producto        Categoria   Precio  Stock
0            Consola            Hogar  1356.77     53
1         Disco Duro       Accesorios   618.86     98
2              Mouse          Oficina   768.86     20
3          Impresora      Electrónica   459.56     69
4        Auriculares  Entretenimiento  1116.00     90
5         Smartphone            Hogar   536.04     69
6            Monitor      Electrónica  1299.05     82
7             Webcam      Electrónica  1149.27     67
8             Cámara          Oficina    56.65     46
9             Laptop            Hogar  1375.86     59

In [ ]:
df_productos["Categoria"]

0              Hogar
1         Accesorios
2            Oficina
3        Electrónica
4    Entretenimiento
5              Hogar
6        Electrónica
7        Electrónica
8            Oficina
9              Hogar
Name: Categoria, dtype: object

In [ ]:
df_productos["Categoria"].unique()

array(['Hogar', 'Accesorios', 'Oficina', 'Electrónica', 'Entretenimiento'],
      dtype=object)

In [ ]:
set(df_productos["Categoria"])

{'Accesorios', 'Electrónica', 'Entretenimiento', 'Hogar', 'Oficina'}

In [ ]:
#Aplicando filtro

df_productos[df_productos["Categoria"] == "Hogar"]

  Nombre de producto Categoria   Precio  Stock
0            Consola     Hogar  1356.77     53
5         Smartphone     Hogar   536.04     69
9             Laptop     Hogar  1375.86     59

In [ ]:
#Aplicamos filtro por cantidad
df_productos[df_productos["Stock"]>60]

  Nombre de producto        Categoria   Precio  Stock
1         Disco Duro       Accesorios   618.86     98
3          Impresora      Electrónica   459.56     69
4        Auriculares  Entretenimiento  1116.00     90
5         Smartphone            Hogar   536.04     69
6            Monitor      Electrónica  1299.05     82
7             Webcam      Electrónica  1149.27     67

In [ ]:
df_productos.shape

(10, 4)

In [ ]:
#Creamos una variable donde almacenar el resultado del filtro

stock_mayor_60 = df_productos[df_productos["Stock"]>60]

stock_mayor_60

  Nombre de producto        Categoria   Precio  Stock
1         Disco Duro       Accesorios   618.86     98
3          Impresora      Electrónica   459.56     69
4        Auriculares  Entretenimiento  1116.00     90
5         Smartphone            Hogar   536.04     69
6            Monitor      Electrónica  1299.05     82
7             Webcam      Electrónica  1149.27     67

In [ ]:
stock_mayor_60.shape

(6, 4)

In [ ]:
df_productos[(df_productos["Categoria"]=="Electrónica") & (df_productos["Stock"]>70)]

  Nombre de producto    Categoria   Precio  Stock
6            Monitor  Electrónica  1299.05     82

# ILOC y LOC

In [ ]:
df_productos.iloc[2]

Nombre de producto      Mouse
Categoria             Oficina
Precio                 768.86
Stock                      20
Name: 2, dtype: object

In [ ]:
df_productos.iloc[2:5]

  Nombre de producto        Categoria   Precio  Stock
2              Mouse          Oficina   768.86     20
3          Impresora      Electrónica   459.56     69
4        Auriculares  Entretenimiento  1116.00     90

In [ ]:
df_productos.iloc[:5]

  Nombre de producto        Categoria   Precio  Stock
0            Consola            Hogar  1356.77     53
1         Disco Duro       Accesorios   618.86     98
2              Mouse          Oficina   768.86     20
3          Impresora      Electrónica   459.56     69
4        Auriculares  Entretenimiento  1116.00     90

In [ ]:
df_productos.iloc[2:]

  Nombre de producto        Categoria   Precio  Stock
2              Mouse          Oficina   768.86     20
3          Impresora      Electrónica   459.56     69
4        Auriculares  Entretenimiento  1116.00     90
5         Smartphone            Hogar   536.04     69
6            Monitor      Electrónica  1299.05     82
7             Webcam      Electrónica  1149.27     67
8             Cámara          Oficina    56.65     46
9             Laptop            Hogar  1375.86     59

In [ ]:
df_productos = df_productos.set_index("Nombre de producto")

In [ ]:
display(df_productos)

                          Categoria   Precio  Stock
Nombre de producto
Consola                       Hogar  1356.77     53
Disco Duro               Accesorios   618.86     98
Mouse                       Oficina   768.86     20
Impresora               Electrónica   459.56     69
Auriculares         Entretenimiento  1116.00     90
Smartphone                    Hogar   536.04     69
Monitor                 Electrónica  1299.05     82
Webcam                  Electrónica  1149.27     67
Cámara                      Oficina    56.65     46
Laptop                        Hogar  1375.86     59

In [ ]:
df_productos.loc["Mouse"]

Categoria    Oficina
Precio        768.86
Stock             20
Name: Mouse, dtype: object

In [ ]:
df_productos.loc["Mouse":]

                          Categoria   Precio  Stock
Nombre de producto
Mouse                       Oficina   768.86     20
Impresora               Electrónica   459.56     69
Auriculares         Entretenimiento  1116.00     90
Smartphone                    Hogar   536.04     69
Monitor                 Electrónica  1299.05     82
Webcam                  Electrónica  1149.27     67
Cámara                      Oficina    56.65     46
Laptop                        Hogar  1375.86     59

In [ ]:
df_productos.loc[:"Monitor"]

                          Categoria   Precio  Stock
Nombre de producto
Consola                       Hogar  1356.77     53
Disco Duro               Accesorios   618.86     98
Mouse                       Oficina   768.86     20
Impresora               Electrónica   459.56     69
Auriculares         Entretenimiento  1116.00     90
Smartphone                    Hogar   536.04     69
Monitor                 Electrónica  1299.05     82

In [ ]:
df_productos.loc["Consola":"Auriculares"]

                          Categoria   Precio  Stock
Nombre de producto
Consola                       Hogar  1356.77     53
Disco Duro               Accesorios   618.86     98
Mouse                       Oficina   768.86     20
Impresora               Electrónica   459.56     69
Auriculares         Entretenimiento  1116.00     90

In [ ]:
df_productos.loc[["Consola","Auriculares"],["Precio","Stock"]]

                     Precio  Stock
Nombre de producto
Consola             1356.77     53
Auriculares         1116.00     90

In [ ]:
hogar = df_productos[df_productos["Categoria"]=="Hogar"]

In [ ]:
df_productos.loc[hogar.index,["Precio","Stock"]]

                     Precio  Stock
Nombre de producto
Consola             1356.77     53
Smartphone           536.04     69
Laptop              1375.86     59

In [ ]:
df_productos

                          Categoria   Precio  Stock
Nombre de producto
Consola                       Hogar  1356.77     53
Disco Duro               Accesorios   618.86     98
Mouse                       Oficina   768.86     20
Impresora               Electrónica   459.56     69
Auriculares         Entretenimiento  1116.00     90
Smartphone                    Hogar   536.04     69
Monitor                 Electrónica  1299.05     82
Webcam                  Electrónica  1149.27     67
Cámara                      Oficina    56.65     46
Laptop                        Hogar  1375.86     59

In [ ]:
df_productos.loc[hogar.index,"Categoria"] = "Casa"

In [ ]:
df_productos

                          Categoria   Precio  Stock
Nombre de producto
Consola                        Casa  1356.77     53
Disco Duro               Accesorios   618.86     98
Mouse                       Oficina   768.86     20
Impresora               Electrónica   459.56     69
Auriculares         Entretenimiento  1116.00     90
Smartphone                     Casa   536.04     69
Monitor                 Electrónica  1299.05     82
Webcam                  Electrónica  1149.27     67
Cámara                      Oficina    56.65     46
Laptop                         Casa  1375.86     59

Desafio:

1. Cargar un archivo .csv con feedback de clientes y crear un dataframe
2. Usar un LLM para clasificar el sentimiento de cada feedback (positivo, negativo, neutro)
3. Agregar esa clasificación al DataFrame

In [ ]:
!pip install -q Groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.7/141.7 kB 2.1 MB/s eta 0:00:00

In [ ]:
import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

client_groq = Groq()

In [ ]:
import pandas as pd

In [ ]:
#Etapa 1
df_reviews=pd.read_csv("/content/reviews.csv")

In [ ]:
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [ ]:
columna_de_reviews = df_reviews["reviewText"]

In [ ]:
columna_de_reviews

0     it works as expected. I should have sprung for...
1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
5     It works, but file writes are a bit slower tha...
6     I bought 2 of those SanDisk 32 GB microSD , us...
7     The memory card is an excellent condition and ...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
12    everything about it was great, except for the ...
13    Used in my phone it's plenty fast and works ju...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
16    good card. work as describes. haven't had any ...
17    I got this because I just couldn't pass up the...
18    It works but the actual R/W speeds are 18/8 MB...
19    Does it's job and fairly cheap for what it's w...
20    Still don't feel is very fast or is just my ph...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
28    The package arrived on time, it's very well pa...
29    Does what it says. Hasn't broken yet, and I ho...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
32    I have two of these and use them for my Galazy...
33    I join the long list of customers who have had...
34    I do not get the advertised speed of 30MB/s, m...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
37    Reliable and inexpensive. However, it's quite ...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

In [ ]:
#Etapa 2

lista_de_analisis=[]
for numero, review in enumerate(columna_de_reviews):
    respuesta = client_groq.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
                {
                    "role": "user",
                    "content": f""" Debes analizar la reseña que yo te envio y retornar un analisis de sentimiento. Debes responder
                    con: Positiva, Negativa o Neutra. Ejemplo:

                    Me encanto el producto -> Positiva
                    El producto no es nada especial -> Neutra
                    No me gusto el producto -> Negativa

                    Debes responder solamente una de esas tres opciones (Positiva, Neutra o Negativa) No agregues texto o explicaciones.

                    Reseña: {review}"""

                }

            ]
        )
    texto = respuesta.choices[0].message.content

    print(f"Review {numero}: {review} -> Sentimiento: {texto}")
    lista_de_analisis.append(texto)

Review 0: it works as expected. I should have sprung for the higher capacity.  I think its made a bit cheesier than the earlier versions; the paint looks not as clean as before -> Sentimiento: Neutra
Review 1: This think has worked out great.Had a diff. bran 64gb card and if went south after 3 months.This one has held up pretty well since I had my S3, now on my Note3.*** update 3/21/14I've had this for a few months and have had ZERO issue's since it was transferred from my S3 to my Note3 and into a note2. This card is reliable and solid!Cheers! -> Sentimiento: Positiva
Review 2: Bought it with Retail Packaging, arrived legit, in a orange envelope, english version not asian like the picture shows. arrived quickly, bought a 32 and 16 both retail packaging for my htc one sv and Lg Optimus, both cards in working order, probably best price you'll get for a nice sd card -> Sentimiento: Positiva
Review 3: It's mini storage.  It doesn't do anything else and it's not supposed to.  I purchased it to add additional storage to my Microsoft Surface Pro tablet which only come in 64 and 128 GB.  It does what it's supposed to and SanDisk has a long standing reputation that speaks for itself. -> Sentimiento: Positiva
Review 4: I have it in my phone and it never skips a beat. File transfers are speedy and have not had any corruption issues or memory fade issues as I would expect from the Sandisk brand. Great card to own. Why entrust your precious files to a slightly cheaper piece of crap? If you lose everything can you forgive yourself for not spending the extra couple bucks on a trusted product that goes through good QA? -> Sentimiento: Positiva
Review 5: It works, but file writes are a bit slower than expected on a USB3 reader.Also, both reads and writes are FASTER with the card inside the standard-size SD adapter (15 MB/s vs 10 write; 45 MB/s vs 22 MB/s read) on the same card reader.  Can't figure why... -> Sentimiento: Neutra
Review 6: I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever -> Sentimiento: Negativa
Review 7: The memory card is an excellent condition and work as described. Dependable and easy to use. An excellent choice for the enthusiast who requires more storage. -> Sentimiento: Positiva
Review 8: I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.Pros-Very good quality materials of construction-Amazing speedUpdate after one year this memory is damaged I can not delete or put new files on it, I can not format this memory, I tried to format with my phone, with my pc, with a camera and nothing, now this is like a 64gb cd, the data in the memory is only available to read but I can not move, or delete it, I bought this memory to be used to backup all my data of my android device but now is only a readable memory I can not write data on it any more, I hope sandisk make a better products in the future!!! Total disagree I will buy a Samsung memory card expected a better quality. -> Sentimiento: Negativa
Review 9: Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.Says "limited lifetime" warranty - BS.  You have ONE MONTH for Eco Zone.  Not only did I lose pictures but now I am out $$ because of a crappy return policy.In the future I will be buying Kingston, not Sandisk.-----------------Update:  Amazon Customer service made good and refunded my purchase price.  I still will not be buying any more Sandisk memory cards however... -> Sentimiento: Negativa
Review 10: more like 8mb/s in my Note 10.1 and that's using SanDisk's own app. A bit faster in my Note II, but still a disappointment for devices with quad core processors. Not sure if it's the card or the device, so benefit of the doubt and four stars. -> Sentimiento: Neutra
Review 11: I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after. I got a replacement card, but I had to send in the old one, giving up any chance of recovering its contents. The new one's worked fine, but failing after 3 months in inexcusable. -> Sentimiento: Negativa
Review 12: everything about it was great, except for the adapter.  It was to tight i had to use a tool to take it back out of the adapter causing me to chip it. so my fault i guess, but i also bought a 16gb version and the adapter for that one was fine. -> Sentimiento: Neutra
Review 13: Used in my phone it's plenty fast and works just like it should. Unexpectedly comes with mini and full SD card size adapters, which is nice. &#34;Fool-proof&#34; packaging or whatever it was, that was laughable. Packaging was decent it just shouldn't have bragged about being impossible to mess up when I messed it up. -> Sentimiento: Positiva
Review 14: This card advertises itself as UHS1 but it's actually UHS50.This means that it will not go up to SDR104 speeds/throughput.Not necessary bad, just false advertising. -> Sentimiento: Negativa
Review 15: I bought this SD card for my android phone thinking that a class 10 will be faster and more reliable than others. it turns out, the difference in class doesn't really matter at least for Android phones. didn't really worth the price difference -> Sentimiento: Negativa
Review 16: good card. work as describes. haven't had any issue with it or going pass metal detectors. no lost files or missing files. -> Sentimiento: Positiva
Review 17: I got this because I just couldn't pass up the deal, $17.99. It has been incredibly fast in my HTC Sensation 4g. Pictures are taken and saved instantaneously. Only had it a few days, but have been very happy. Shipping was fast and the packaging was easy to open which is always great in my book. Only issue I had was I had to format it on my computer first before my phone was able to recognize it. -> Sentimiento: Positiva
Review 18: It works but the actual R/W speeds are 18/8 MB/s, not even Class 10. It should be marketed as "Sandisk Basic", not Sandisk Ultra", unless they mean ultra slow. Now is 2014 and there is no excuse for such slow card from Sandisk.*** UPDATE ***I have redone the test with NotePro 12.2" instead of using non UHS-I PC and the latest results are 32/8.6MB/s. Since the read speed hits 30, I believe the device is DHS-I ready. Still underwhelmed by the write speed though. -> Sentimiento: Negativa
Review 19: Does it's job and fairly cheap for what it's worth. I had to return my first one and exchange it for another because the first one was defective. Sandisk really needs to do better quality assurance on their products. The second one works perfectly fine. I use it for my GoPro camera. -> Sentimiento: Neutra
Review 20: Still don't feel is very fast or is just my phone, I guess I will need to remove it and run some R/W tests. Still Its ok. -> Sentimiento: Neutra
Review 21: I bought 64GB version of the card to use with GoPro Hero 3 black edition.  It didn't work out.  The card worked OK if camera was set to resolution with lower bit rates.  E.g. worked fine in 720p with protune on, or 1080p with protune off.  However, in 1080p with protune on (bitrate is just shy of 6 MB/s in this mode -- much higher then with protune turned off) it was nothing but trouble.  Camera would sometime work, and sometime randomly stop recording for no obvious reason.  I first suspected camera, but testing with different SD cards, it ended up being SanDisk's card that was at fault.  My spare card, an old and cheap 16GB PNY (also class 10), worked just fine under same conditions and with same camera settings.Once it was obvious it was problem with the card, I found people on GoPro's forums that had trouble with this specific card as well (well, you always find these only after you figure it out for yourself, right?).  Anyhow, I did some speed tests with the card by doing simple write of 1GB file full of zeros using Unix dd utility to copy 1GB of zeros from /dev/zero (where else would you find that many zeros ;-) onto a file on the card.  The result was that on average, SanDisk's card would manage about 10.2 MB/s.  Just barely above the bar for class 10 card.  However, that was average over 1GB.  During the write test, the speed was oscillating with many spikes and drops.  Drops were as low as 7MB/s.  Uh.  I thought write speed of class 10 card should never dip below 10 MB/s?  For comparison, my old cheap class 10 PNY card was chugging along at constant 13 MB/s under the same test.  No spikes and no drops in speed.The card will probably work fine in most devices, as bitrates when recording 1080p video are often low enough and/or camera might have huge buffer.  But if you want to use it to record video at high bitrates, and your device doesn't have huge buffer to compensate for speed bumps of this card, you may run into trouble.  Be wary of using it in Hero3 in modes that have higher bit rates (e.g. 1080p with protune enabled).SanDisk's website lists part numbers as SDSDQUI-064G with adapter, and SDSDQUA-064G without adapter.  This conflicts with product description on Amazon.  While this is likely just Amazon not getting product description right again (a bit too common thing), it's interesting to note.[Update Apr 20 2013]:Some numbers from testing the card.  The test is extremely simple.  Write out 1GB of zeros onto the card using standard Unix dd command to read 128KB blocks of zeroes from special device /dev/zero and write it onto the card.  128KB * 8192 = 1GB.  dd displays transfer stats once it finishes.  While dd was running, I run iostat in second terminal displaying 1 second interval stats as a measure of current speed.  This was done on the Mac.  dd command line can be used as-is to repeat test on Linux system, however iostat command is different on Linux and would need to be modified slightly.  I choose 128KB block size, as that seems to be what device drivers merges sequential writes into anyhow.  Using different block sizes, results are comparable.$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 101.578307 secs (10570582 bytes/sec)So, 10 MB/s and all is good? Right? Wrong! iostat running in parallel with above dd command recorded this:$ iostat -d -w 1 disk2disk2KB/t tps MB/s123.11 76 9.12116.61 185 21.04122.94 49 5.88128.00 41 5.12128.00 89 11.11128.00 134 16.73128.00 69 8.61128.00 61 7.62128.00 99 12.36[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]IMO, the last column should never dip under 10MB/s for card labeled class-10.For comparison, same test run against Samsung Pro 64GB micro-SD card:$ dd if=/dev/zero of=test bs=131072 count=81928192+0 records in8192+0 records out1073741824 bytes transferred in 52.869111 secs (20309436 bytes/sec)$ iostat -d -w 1 disk2disk2KB/t tps MB/s125.30 138 16.86117.73 157 18.03123.04 150 18.00128.00 159 19.86128.00 156 19.47126.45 160 19.73128.00 150 18.72128.00 154 19.22128.00 153 19.11[ ... and so on until dd finishes writing 1GB of zeros to the card ... ]So, Samsung is on average 2x faster, but more importantly it's speed is much more constant.  And critically important, it never dips under 10MB/s. -> Sentimiento: Negativa
Review 22: I have an old SanDisk SD card that still works. I thought their new cards would be just as reliable, but I was wrong.The microsd card failed yesterday inside my phone. I used the adapter to connect it to my computer, but it wouldn't mount.I bought this directly from Amazon and not a third party vendor, so I know it's genuine SanDisk. -> Sentimiento: Negativa
Review 23: Used it in my Galaxy Note 2 for the past 16 months. All the sudden it is no longer writable. I tried many ways to reformat the card. Even Windows says format successful but all files remain after I remove and re-insert the card. Since I have private files in the card I'm not able to delete. I do not want to sent it back to SanDisk for replacement. -> Sentimiento: Negativa
Review 24: Worked great in my galaxy s4--until it didn't work at all for some unknown reason. Used it for about 4 months before it crapped out. BACK UP YOUR DATA WITH ALL THESE THINGS, THOUGH.... -> Sentimiento: Negativa
Review 25: I bought this on August of 2013.  As of April 2014 the card stopped functioning.  It can still be read, but the writing capability is gone.  That's less than one year.  I'm extremely disappointed in the longevity of this card.  My usage of it has been on my Galaxy S4.  I have about 40Gb of data in it.  Guess I'm going to have to look for another card that has a longer lifespan than this one. -> Sentimiento: Negativa
Review 26: So this product is a large disappointment...bought it to use in my tablet but the card is forever getting corrupted....I've reformatted the card a few times but it's to the point now that even a reformat doesn't work..  Wasted money...don't recommend purchasing. -> Sentimiento: Negativa
Review 27: I will keep it short and sweet for potential buyers looking for facts and not b.s.I own two of the 32gb size of these cards for about 3 months now. They do work fairly well with cell phones and tablets, yet not so good with cameras, in fact these cards failed to work with my GoPro Hero3 camera and the customer service rep from Gopro claimed (and I happen to agree with him) that this card is not a true class 10 card let alone UHS-1.Benchmarks with my evo 4g with all allocation sizes the write speed never passed beyond 8mb/s while read speeds wondered around 25mb/s far below advertised speeds, well write speeds arent technically advertised (probably because they are of class 4 level)Benchmarks with crystal mark reported speeds even lower (due to adapter) with write speeds around 6mb/s while read speeds wondered around 20mb/s.Needless to say, if you are not worried about speeds and only about storage, these are perfect. If you want to use them for shooting high definition raw footage however, I suggest you not to loose your money on this, because even if your write speeds are around 10mb/s as the card begins to decay it will slow down to become useless.Again this review is based on GoPro camera and high definition raw recording.. For cell phones or for storage it works perfectly well with a bit of false advertisement.. -> Sentimiento: Negativa
Review 28: The package arrived on time, it's very well packed and it's got an adapter. It works perfectly with my phone, though it doesn't allow a computer format, once it's been on the phone, so it asks you to erase everything before you use it on a computer. So if you're planning on buying this for different purposes and devices, gotta be aware of this. I just need for my phone, so I transfer files with my usb cable, that works just right. I also give it a 3 star because it says there are 64gb, but even when it's totally formatted it only reaches to 60gb..sooo, I don't know where my other 4 gb are...anyways, overall it's working well. I do think it's expensive for what it is. -> Sentimiento: Neutra
Review 29: Does what it says. Hasn't broken yet, and I hope it doesn't break. I've had luck with this brand before. Usually get bored with the product before it breaks. -> Sentimiento: Positiva
Review 30: Thus microSD card worked fine for a year in my Samsumg Note II. I mostly used it to listed to downloaded music from Spotify. It has actually failed &#34;twice&#34;. When it failed the first time (the phone couldn't &#34;see&#34; that I had a card installed) I thought maybe something had merely corrupted it, so I formatted it, put it back in my phone, and re-downloaded all my playlists. It worked for two months and then failed again. I don't plan to try formatting it again, I'll switch to a different brand of card. -> Sentimiento: Negativa
Review 31: I think this is probably a fine product, but it wasn't compatible with my Samsung Galaxy S3 phone. Formatted as exFAT (as it came from the factory), didn't work at all, but that's a known problem with the GS3. But even after reformatting to FAT32, the card caused my phone to reboot multiple times. -> Sentimiento: Negativa
Review 32: I have two of these and use them for my Galazy Note 2. It's great having the flexibility to keep extra storage with you for your 'phablet'.So far they have done what they are intended to do. -> Sentimiento: Positiva
Review 33: I join the long list of customers who have had their SanDisk die on them.  Customer service from SanDisk has been helpful.  They pay for UPS shipping for the return and promise a 7-10 day turn around once the defective disk has been returned.  Still it's a pain to deal with and I lost some photographs.UPDATE: SanDisk sent me a replacement and it seems to be working.  If the replacement goes bad, I'll be back to complain:)SECOND UPDATE: All is well with the replacement so I'm giving it three stars. -> Sentimiento: Neutra
Review 34: I do not get the advertised speed of 30MB/s, more like a 200-300KB/s on my Galaxy S4. At least it gives me a lot of extra storage space, for a phone it works nicely if you don't need to transfer big files. -> Sentimiento: Neutra
Review 35: the micro sd works great as described. but beware that the micro sd adapters are faulty. the micro sd will get stuck in the adapter. you will have to carefully rip apart the adapter to get the micro sd out thus damaging the apapter. -> Sentimiento: Negativa
Review 36: than i expected. I don't know if it would kill any manufacturers to actually have a memory card or stick or device to actually HAVE Available the advertised capacity. Fortunately l learned that the advertised and actual available memory are TWO SEPARATE THINGS before i bought it, always scroll down and read the technical spec of a device or anything before you buy as that way ideally, your actually informed. Let the buyer beware, is more appropriate every day as most things are not exactly as they seem. And if it's food and cheap, it's likely cancer causing and don't feed your body and your car in the same place. -> Sentimiento: Negativa
Review 37: Reliable and inexpensive. However, it's quite slow, far, far slower than the 64GB samsung pro microsdxc. The Samsung works well for interactive use while I would only use this Sandisk card for applications where speed isn't important. -> Sentimiento: Neutra
Review 38: I bought this primarily to use in my Surface Pro. It would randomly dismount itself. I do not know if it was the Surface's fault or the card's fault. Upon doing a little internet searching, I found this to be a common problem with Sandisk cards and the Surface Pro. I used another brand microSDXC and it has worked fine. -> Sentimiento: Negativa
Review 39: I really don't know what to think about this I got it thinking it would solve my memory problems but that's not the case turns out you can only put certain things on this and of course none of the thingsthat are eating up your memory on.your will go there is a way to swap your internal memory for your external card but it's not easy and you have to root  your phone -> Sentimiento: Negativa

In [ ]:
lista_de_analisis

['Neutra',
 'Positiva',
 'Positiva',
 'Positiva',
 'Positiva',
 'Neutra',
 'Negativa',
 'Positiva',
 'Negativa',
 'Negativa',
 'Neutra',
 'Negativa',
 'Neutra',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Positiva',
 'Negativa',
 'Neutra',
 'Neutra',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Negativa',
 'Neutra',
 'Positiva',
 'Negativa',
 'Negativa',
 'Positiva',
 'Neutra',
 'Neutra',
 'Negativa',
 'Negativa',
 'Neutra',
 'Negativa',
 'Negativa']

In [ ]:
#Etapa 3

df_reviews["Sentimiento"] = lista_de_analisis

df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Sentimiento
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Neutra
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positiva
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Positiva
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Positiva
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positiva