<a href="https://colab.research.google.com/github/gvasquezcrs/python_ia_aplicada/blob/main/Aula_6_Python_Inteligencia_Artificial_Aplicada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 6

In [ ]:
edad=int(input("Ingrese su edad"))

Ingrese su edadsdfsdafasf

ValueError: invalid literal for int() with base 10: 'sdfsdafasf'

In [ ]:
persona= 6
persona2="Juan, Pedro, Laura, Maria"
persona+persona2

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
try:
  edad = int(input("Ingrese su edad"))
except:
  print("No ingresaste un número")

Ingrese su edadasdfsdf
No ingresaste un número

In [ ]:
try:
  edad = int(input("Ingrese su edad"))
except ValueError as ve:
  print("No ingresaste un número")
  print("El error es:",ve)

Ingrese su edaddfdsf
No ingresaste un número
El error es: invalid literal for int() with base 10: 'dfdsf'

In [ ]:
try:
  persona= 6
  persona2="Juan, Pedro, Laura, Maria"
  persona+persona2
except ValueError as ve:
  print("No ingresaste un número")
  print("El error es:",ve)
except TypeError as te:
  print("No puedes sumar un número con un string")
  print("El error es:",te)
finally:
  print("Finalizó la ejecución")

No puedes sumar un número con un string
El error es: unsupported operand type(s) for +: 'int' and 'str'
Finalizó la ejecución

In [ ]:
df_reviews
df_reviews["Sentimiento"]

0       Neutra
1     Positiva
2     Positiva
3     Positiva
4     Positiva
5       Neutra
6     Negativa
7     Positiva
8     Negativa
9     Negativa
10      Neutra
11    Negativa
12      Neutra
13    Positiva
14    Negativa
15    Negativa
16    Positiva
17    Positiva
18    Negativa
19      Neutra
20      Neutra
21    Negativa
22    Negativa
23    Negativa
24    Negativa
25    Negativa
26    Negativa
27    Negativa
28      Neutra
29    Positiva
30    Negativa
31    Negativa
32    Positiva
33      Neutra
34      Neutra
35    Negativa
36    Negativa
37      Neutra
38    Negativa
39    Negativa
Name: Sentimiento, dtype: object

In [ ]:
df_reviews["Sentimiento"] == "Negativa"

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8      True
9      True
10    False
11     True
12    False
13    False
14     True
15     True
16    False
17    False
18     True
19    False
20    False
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28    False
29    False
30     True
31     True
32    False
33    False
34    False
35     True
36     True
37    False
38     True
39     True
Name: Sentimiento, dtype: bool

In [ ]:
df_reviews_negativas = df_reviews[df_reviews["Sentimiento"] == "Negativa"]

In [ ]:
df_reviews_negativas

In [ ]:
reviews_negativas =df_reviews_negativas["reviewText"]
reviews_negativas

6     I bought 2 of those SanDisk 32 GB microSD , us...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
11    I used this for a few months in my phone, then...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
18    It works but the actual R/W speeds are 18/8 MB...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

In [ ]:
reviews_negativas_unidas= "####".join(reviews_negativas)
reviews_negativas_unidas

In [ ]:
respuestas_cat = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": f"""Eres un analista de datos, te pasaré muchas reseñas separadas por "####"
                Quiero que encuentres *exactamente* 5 categorias diferentes para cada tipo de reclamo.
                Quiero que retornes las cinco categorias como una lista de palabras separadas por comas, sin tildes y en minúsculas.
                La respuesta debe ser solamente las cinco categorias, separadas por comas
                 Ejemplo:

                          "uso, calidad, duracion, estado, aspecto"

                          Reseña: {reviews_negativas_unidas}"""
        }
       ]
    )
print(respuestas_cat.choices[0].message.content)

calidad, duracion, velocidad, compatibilidad, capacidad

In [ ]:
categorias=respuestas_cat.choices[0].message.content

In [ ]:
lista_de_categorias = categorias.split(", ")
lista_de_categorias

['calidad', 'duracion', 'velocidad', 'compatibilidad', 'capacidad']

# JSON

In [ ]:
{
    "name": "Chris",
    "age": 23,
    "address": {
        "city": "New York",
        "country": "America"
    },
    "friends": [
        {
            "name": "Emily",
            "hobbies": [
                "biking",
                "music",
                "gaming"
            ]
        },
        {
            "name": "John",
            "hobbies": [
                "soccer",
                "gaming"
            ]
        }
    ]
}

In [ ]:
respuestas_cat = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
                "role": "user",
                "content": f"""Eres un analista de datos, te pasaré muchas reseñas separadas por "####"
                Quiero que encuentres *exactamente* 5 categorias diferentes para cada tipo de reclamo.
                Las categorias deben ser solo una palabra.
                Despues quiero que me retornes la respuesta en formato JSON con tres claves:
                - "review_original": Aqui va la review original;
                - "review_es": Reseña traducida al español;
                - "categoria": Categoria definida correspondiente a esa reseña.

                Ejemplo:

                {{"review_original": "I didn´t like the color of the product"}}

                La respuesta debe ser SOLO y UNICAMENTE el texto en JSON

                          Reseñas: {reviews_negativas_unidas}"""
            }
       ],
    response_format={"type": "json_object"},
    max_tokens=4096
    )
json_de_reviews_clasificadas = respuestas_cat.choices[0].message.content
print(json_de_reviews_clasificadas)

[
{
  "review_original": "I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever",
   "review_es": "Compre 2 de esos SanDisk 32 GB microSD, los usé en mi Galaxy Note y Galaxy S4. El primero, mi teléfono empezó a decir que se quitó, luego lo reconoció de nuevo :) luego se murió. Pensé que solo era suerte, lo enchufé al segundo :) se mantuvo durante alrededor de 2 meses y se murió de repente ¡y perdí todo! Nunca volveré a comprar de SanDisk... nunca",
   "categoria": "Falla"
},

{
   "review_original": "I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.",
   "review_es": "Compre esta tarjeta micro SD después de algunos problemas con otra que compré de Kingston, puedo decir que SanDisk es de otra calidad, esto es lo mejor, mi teléfono i9300 puede leer un 64GB muy rápido, la velocidad de transferencia de datos desde mi pc a mi es impresionante, si estás buscando almacenamiento adicional para tu teléfono, para música, imágenes y otros tipos de archivos, esto es para ti.",
   "categoria": "Calidad"
},

{
   "review_original": "Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.",
   "review_es": "Pedí este para un Galaxy S3. Duró unos meses y luego se rompió. No es accesible en varios PC diferentes.",
   "categoria": "Ruptura"
},

{
   "review_original": "I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after.",
   "review_es": "Lo usé durante unos meses en mi teléfono, luego decidió dejar de montar. Perdí algunas fotos de mascotas que murieron poco después.",
   "categoria": "Pérdida"
},

{
   "review_original": "This card advertises itself as UHS1 but it's actually UHS50.",
   "review_es": "Esta tarjeta se anuncia como UHS1 pero en realidad es UHS50.",
   "categoria": "Publicidad"
}
]

In [ ]:
import json

dic_reviews_negativas_clasificadas = json.loads(json_de_reviews_clasificadas)

In [ ]:
dic_reviews_negativas_clasificadas

[{'review_original': "I bought 2 of those SanDisk 32 GB microSD , used them on my Galaxy Note and Galaxy S4First one , my phone started saying it was removed , then recognize it again :) then diedI thought it's just a luck , plugged in the 2nd one :) stayed for about 2 months and died suddenly ! and lost everythingnever buying from SanDisk again .. ever",
  'review_es': 'Compre 2 de esos SanDisk 32 GB microSD, los usé en mi Galaxy Note y Galaxy S4. El primero, mi teléfono empezó a decir que se quitó, luego lo reconoció de nuevo :) luego se murió. Pensé que solo era suerte, lo enchufé al segundo :) se mantuvo durante alrededor de 2 meses y se murió de repente ¡y perdí todo! Nunca volveré a comprar de SanDisk... nunca',
  'categoria': 'Falla'},
 {'review_original': 'I bougth this micro SD card after some trubles with other that i got from Kingston, i can tell that SanDisk is other quality, this is the best, my i9300 phone can read a 64GB very fast, the dta transfer speed from my pc to my is amazing, if you are looking for additional storage to you phone, for music, pictures and other type of files, this is for you.',
  'review_es': 'Compre esta tarjeta micro SD después de algunos problemas con otra que compré de Kingston, puedo decir que SanDisk es de otra calidad, esto es lo mejor, mi teléfono i9300 puede leer un 64GB muy rápido, la velocidad de transferencia de datos desde mi pc a mi es impresionante, si estás buscando almacenamiento adicional para tu teléfono, para música, imágenes y otros tipos de archivos, esto es para ti.',
  'categoria': 'Calidad'},
 {'review_original': "Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.",
  'review_es': 'Pedí este para un Galaxy S3. Duró unos meses y luego se rompió. No es accesible en varios PC diferentes.',
  'categoria': 'Ruptura'},
 {'review_original': 'I used this for a few months in my phone, then it decided to quit mounting. I lost some pictures of pets who died shortly after.',
  'review_es': 'Lo usé durante unos meses en mi teléfono, luego decidió dejar de montar. Perdí algunas fotos de mascotas que murieron poco después.',
  'categoria': 'Pérdida'},
 {'review_original': "This card advertises itself as UHS1 but it's actually UHS50.",
  'review_es': 'Esta tarjeta se anuncia como UHS1 pero en realidad es UHS50.',
  'categoria': 'Publicidad'}]

In [ ]:
len(dic_reviews_negativas_clasificadas)

5

In [ ]:
dic_reviews_negativas_clasificadas[2]

{'review_original': "Ordered this for a Galaxy S3.  Lasted a few months and then broke.  Is not accessible on several different PC's.",
 'review_es': 'Pedí este para un Galaxy S3. Duró unos meses y luego se rompió. No es accesible en varios PC diferentes.',
 'categoria': 'Ruptura'}

# Desafío Final (usando un IDE)

**1.** Cargar un archivo `.txt`, donde cada línea será un elemento de una lista de Python.

**2.** Mandársela al modelo que estás corriendo localmente para extraer, en formato JSON, donde cada ítem tendrá:
- `usuario`
- `reseña original`
- `reseña_es`
- `evaluación` *(Positiva, Negativa, Neutra)*

**3.** Transformar la respuesta del modelo en una lista de diccionarios Python.

**4.** Crear una función que, dada una lista de diccionarios, recorra la lista y haga 2 cosas:

- **a)** Contar la cantidad de evaluaciones positivas, negativas y neutras.
- **b)** Unir cada ítem de esa lista en una variable de tipo `string` con algún separador.

> Al final, retornar ambas cosas.